version: "3.8"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 9976522374
      DB_NAME: employeemanagement
    command: ["./wait-for-it.sh", "db:5432", "--", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
  
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: employeemanagement
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 9976522374
    ports:
      - "5432:5432"

